### PR TITLE
no "ifnull" in SQLServer

### PR DESCRIPTION
**Pull request by Shaddix**
no "ifnull" in SQLServer
fix the issue where Database column and Property name have different casing

### CODE REVIEW

**Comment by ethanli83** [comment]
Hi @Shaddix,

Thanks for the "ifnull" fix. It looks good.

For the change in SqlColumn. 

$"{this}" behaves quite differently from $"{Alias}", you can have a look at the ToString method in SqlColumn. 

What's the problem you try to fix? Can you give me an example query?

Many thanks,

**Comment by Shaddix** [comment]
In ConsoleApp add an attribute  `[Column("name")]` to the Blog.Name property.
Then run the query 
`var query = db.Blogs.Select(x => new { x.Name });`

**Comment by ethanli83** [comment]
Hi @Shaddix,

Is it related to PostgresQl? kkkk

I think it would work better to change line 29 in SqlColumn 
from
```
return !string.IsNullOrEmpty(Alias) && !Alias.Equals(Name, StringComparison.CurrentCultureIgnoreCase)
```
to 
```
return !string.IsNullOrEmpty(Alias) && !Alias.Equals(Name)
```

This will make sure the Alias is used if the case is not the same

**Comment by Shaddix** [comment]
no, I'm basically working with SQL server (btw, this is not db-related :))

You're right, pushed the change

**Comment by ethanli83** [comment]
Hi @Shaddix,

I think there are some unit tests broken for the 'ifnull' change. Do you mind to have a look?

**Comment by ethanli83** [comment]
ah~, that makes sense, thx

**Pull request merged**
