### PR TITLE
#30 Support boolean columns in SQL Server

### PR DESCRIPTION
**Pull request by Shaddix**
Fixes issue #30

### CODE REVIEW

**Comment by ethanli83** [comment]
hi @Shaddix,

Many thanks for the fix! 

Just a small thing, since the value for a bit type is 0, 1, null, it maybe better to do 
```
return (bool)val ? 1 : 0;
```

**Comment by Shaddix** [comment]
I'm not a PostgreSQL expert, but I [read](https://www.postgresql.org/docs/9.1/static/datatype-boolean.html) that the valid values for bool are '0' and '1'. If it works without quotes (don't have PostgreSQL installed, unable to verify), I'll definitely change that!

**Comment by ethanli83** [comment]
Hi @Shaddix,

You are correct with PostgresQl, 1 will not work with it. Thanks!

Also, if you ever want to try out some sql on different database next time, try out http://sqlfiddle.com. It has been very helpful to me.

I will merge the pull request and push all a new package later along with some other fixes. 

Cheers,

**Comment by Shaddix** [comment]
thanks for the sqlfiddle link!

**Pull request merged**
